### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by Dennis1987m** [Newan/ioBroker.bluelink#1]
Beim Starten des Adapters erhalte ich folgende Zeile im LOG:

(17078) ManagedBluelinkyError: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.kia.com:8080/api/v1/user/signin - {"errId":"9034b41a-24ec-4737-b1db-2bffc65b5a5e","errCode":"4

Habe einen IONIQ Facelift. Stelle bei Marke auch Hyundai ein - jedoch stellt sich das nach dem Speichern wieder auf KIA um. Liegt es vielleicht daran?

**Comment by Newan** [comment]
> Beim Starten des Adapters erhalte ich folgende Zeile im LOG:
> 
> (17078) ManagedBluelinkyError: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.kia.com:8080/api/v1/user/signin - {"errId":"9034b41a-24ec-4737-b1db-2bffc65b5a5e","errCode":"4
> 
> Habe einen IONIQ Facelift. Stelle bei Marke auch Hyundai ein - jedoch stellt sich das nach dem Speichern wieder auf KIA um. Liegt es vielleicht daran?

Hyundai im nächsten Update ;). Melde mich bzw machen wir am besten mal Forum auf!

**Comment by Dennis1987m** [comment]
Ah okay. Perfekt. Vielen Dank 👍🏻

Am 25.03.2021 um 17:19 schrieb Newan ***@***.***>:

﻿
Beim Starten des Adapters erhalte ich folgende Zeile im LOG:

(17078) ManagedBluelinkyError: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.kia.com:8080/api/v1/user/signin - {"errId":"9034b41a-24ec-4737-b1db-2bffc65b5a5e","errCode":"4

Habe einen IONIQ Facelift. Stelle bei Marke auch Hyundai ein - jedoch stellt sich das nach dem Speichern wieder auf KIA um. Liegt es vielleicht daran?

Hyundai im nächsten Update ;). Melde mich bzw machen wir am besten mal Forum auf!

**Comment by Newan** [comment]
fixed.
Im Admin-Gui kann die Selectbox beim abspeichern noch auf Kia stehen bleiben, hier muss ich seperat schauen.
Im Debug -Log müsste unter Brand aber "H" stehen

**Comment by Dennis1987m** [comment]
Zwar wird jetzt im Debug Hyundai angezeigt, ich bekomme jetzt aber eine ganz ähnliche Fehlermeldung. Mache ich irgendetwas falsch?

Hier die Fehlermeldung:



(4306) ManagedBluelinkyError: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin - {"errId":"f29152ef-b5f0-477c-ba15-88f0eedf8156","errCode":

**Comment by Newan** [comment]
Schickst du mir mal deine geänderten Zugangsdaten: info@newan.de

dann schau ich mal genauer!

**Comment by Newan** [comment]
Andere Hyundai-Fahrer abwarten, ob Probleme mit dem Account oder für alle Hyundai

**Comment by Newan** [comment]
Zitat aus dem Forum "Die Anleitung sollte beinhalten, dass man sich zwingend in der App abmelden, neu anmelden und mit dem neuen Hyundai Account statt Bluelink verbinden muss. Ein neues Passwort kann, muss aber nicht gewählt werden. Dann die Anmeldedaten nicht von Bluelink sondern vom Hyundaiaccount nehmen. Wobei ich da nicht sicher bin, da es bei mir identisch ist."

Scheint für Hyundai nun zu funktionieren
