### ISSUE TITLE
Keine Verbindung mehr mit KIA

### ISSUE THREAD

**Issue by tugsi** [Newan/ioBroker.bluelink#10]
Bisher vorgestern lief der Adapter einwandfrei, aber seitdem kann er sich nicht mehr einloggen.
Ich habe keine Passwörter oder ähnliches geändert und meine UVO-App funktioniert auch noch wie gehabt.

Folgende Meldung kommt:
ManagedBluelinkyError: @EuropeController.login: [401] Unauthorized on [POST] https://prd.eu-ccapi.kia.com:8080/api/v1/spa/notifications/register - {"retCode":"F","resCode":"4017","resMsg":"Invalid request value - Invalid Application Id.","msgId":"9b8693ae-5658-4c47-825d-488149953b76"}

**Comment by kantega-ea** [comment]
Ja, er lief bis gestern 16:00 Uhr. Aber auch zum Beispiel die App PUMP kann seit dieser Zeit nicht auf die API zugreifen.

Mit freundlichen Grüßen 

Christian Hoffmann
An der Höll 9e
99817 Eisenach
Telefon: 01716819901

**Comment by Newan** [comment]
Testet al das ihr in den Ordner geht wo der Adapter installiert wird. und dann ein `npm update` damit sollte die Abhängigkeiten aktualisiert werden.

Alternativ installiert den Adapter einmal neu.

**Comment by tugsi** [comment]
Adapter habe ich neu installiert und klappt nicht.
Ich habe auf meinen Raps auch die bluelinky_Version zum testen drauf, die verbindet sich auch nicht mehr.
Da scheint etwas an der API geändert worden zu sein.
Wie auch @kantega-ea schon schrieb, bei PUMP gehts auch nicht mehr, hab von den Entwicklern eine Testversion und denen auch schon ein Feedback geschickt.

**Comment by Newan** [comment]
ok dann warten wir mal ab bis die lib aktualisiert wurde

**Comment by Newan** [comment]
Laut Forum hilft ein Neuinstallation damit die Library aktualisiert wird

**Comment by tugsi** [comment]
> Laut Forum hilft ein Neuinstallation damit die Library aktualisiert wird

Kann ich bestätigen. Deinstallation und eine Neuinstallation brachte jetzt die Besserung, damals war die Library noch nicht aktualisiert.
Also klappt jetzt wieder.
