### ISSUE TITLE
Adapter not Login

### ISSUE THREAD

**Issue by anwelti** [Newan/ioBroker.bluelink#102]
**Describe the bug**  

**To Reproduce**  
1. Go to 'adapter config'
2. Click on 'input credantials'
3. Scroll down to 'save and exit'

**Screenshots & Logfiles**  
Protokoll:
next auto login attempt in 1 hour or restart adapter manual
--
bluelink.0 | 2023-07-12 21:53:08.392 | error | Server is not available or login credentials are wrong
bluelink.0 | 2023-07-12 21:53:08.391 | error | ManagedBluelinkyError: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.kia.com:8080/api/v1/spa/notifications/register - {"retCode":"F","resCode":"4002","resMsg":"Invalid request body - Block the UVO app id.","msgId":"969b820d-f32c-4e4e-a94e-dc9fbf40368c"}

**Versions**
Adapter version: 2.3.2
 - JS-Controller version: 5.0.7
 - Node version: 19.4.0
 - Operating system: Ubuntu 22.04 , 64bit

**Comment by arteck** [comment]
server issue
