### ISSUE TITLE
Keine Verbindung mehr mit Hyundai

### ISSUE THREAD

**Issue by Michaelnorge** [Newan/ioBroker.bluelink#11]
Genau wie mein Vorgänger, bekomme ich die selbe Fehlermeldung bei meinem Hyundai.
Neustart/Neuinstallation hat nichts gebracht.
`

bluelink.0 | 2021-06-04 14:01:32.474 | error | ManagedBluelinkyError: @EuropeController.login: [401] Unauthorized on [POST] https://prd.eu-ccapi.hyundai.com:8080/api/v1/spa/notifications/register - {"retCode":"F","resCode":"4017","resMsg":"Invalid request value - Invalid Application Id.","msgId":"xxxxxxxx-xxyxx-xxxx-xxxxx-xxxxxxxxxxxxx"}
-- | -- | -- | --

`
Kann es sein, daß der Server merkt daß keine Abfrage der App sondern vom Bluelink-Adapter kommt?

**Comment by tugsi** [comment]
Ich hatte vor einigen Tagen das es auch nach einer Neuinstallation nicht klappte (KIA), heute neuinstalliert und jetzt klappt es.
Eventuell nochmal probieren, weiß jetzt nicht, wann die Library, worauf Newan zurückgreift, upgedatet wurde...

**Comment by Newan** [comment]
Ja bitte Neuinstallation oder npm update im adapter Ordner. Wenns geht aktualisieren wir einfach die Abhängigkeiten

**Comment by SvenP99** [comment]
Bei mir hat eine Neuinstallation nichts gebracht. Bekomme immer noch die Fehlermeldung
 (10992) ManagedBluelinkyError: @EuropeController.login: [401] Unauthorized on [POST] https://prd.eu-ccapi.kia.com:8080/api/v1/spa/notifications/register - {"retCode":"F","resCode":"4017","resMsg":"In

**Comment by Newan** [comment]
Liegt an Hyundai/Kia, müssen auf update von bluelink warten

**Comment by Newan** [comment]
Version 1.0.6 testeb
