### ISSUE TITLE
@EuropeVehicle.status: [503] Service Unavailable

### ISSUE THREAD

**Issue by Duggles1301** [Newan/ioBroker.bluelink#122]
Every Time when the Adapter wants to update the data by the configurated Interval it comes this error:

Error on API-Full-Status - Fallback GetNormalStatus

Error on API-Request Status, ErrorCount:1

@EuropeVehicle.status: [503] Service Unavailable on [GET] https://prd.eu-ccapi.kia.com:8080/api/v2/spa/vehicles/f237e4e0-95c3-4291-8e5c-0b39d691271b/status - {"retCode":"F","resCode":"5031","resMsg":"Unavailable remote control - Service Temporary Unavailable","msgId":"d42b515b-9df5-441d-be0c-c0498f7a5cf8"}

**Comment by pokeplayer2** [comment]
I got the same issue, thx for opening the request.

**Comment by Ilovegym66** [comment]
this error is nothing with the iobroker-Adapter, the Hyundai-Servers are down, thats it.
Open an issue at Hyundai, please :-)
