### ISSUE TITLE
No refresh possible after manual charging start

### ISSUE THREAD

**Issue by Narolakk** [Newan/ioBroker.bluelink#126]
**Describe the bug**  
If I start the charging process via the adapter and then perform 
a force refresh (car/server), I get an API error, 
after restarting the adapter everything works again.

**To Reproduce**  
1. Start Charging
2. Force Refresh (Car/Server)

**Screenshots & Logfiles**  
![Screenshot 2024-01-16 214610](https://github.com/Newan/ioBroker.bluelink/assets/48066111/fcbdc439-5e10-4a88-8dec-81511357482a)

**Versions:**  
 - Adapter version: v2.3.6
 - JS-Controller version:v 5.0.17
 - Node version: v18.19
 - Operating system: <DSM7.2.1/Docker>

**Comment by arteck** [comment]
you can not send many request at same time.. sry

**Comment by Narolakk** [comment]
Even if i wait and then send another command, this does not work until the adapter has been restarted. in the screenshot you can also see that a certain amount of time has passed between the requests.
