### ISSUE TITLE
After a command has been sent, the adapter only works again after a restart

### ISSUE THREAD

**Issue by PLCHome** [Newan/ioBroker.bluelink#127]
![image](https://github.com/Newan/ioBroker.bluelink/assets/29116097/7b0a7e9f-dfcc-4f10-bea8-894ceb2cdc0a)

After a command has been sent, the adapter only works again after a restart.
Before restarting after the command, there is always a message that the DeviceID is invalid.
Currently I send the command and then restart the adapter.

It doesn't matter which command climate on, climate off or charging like describen by @Narolakk

"No refresh possible after manual charging start #126"
is the same issue but closed.

Is there perhaps something missing that the command has ended? The behavior is as if you were asking too early but the app already shows it and there are minutes in between.

**Versions:**  
 - Adapter version: 2.3.6
 - JS-Controller version: 5.0.17
 - Node version: 18.19.0
 - Operating system: linux

It works with the restart script:
![image](https://github.com/Newan/ioBroker.bluelink/assets/29116097/7d79bc16-6999-496e-b0c4-72a59bde9fbf)

**Comment by arteck** [comment]
Adapter version: 2.3.6 its old..
