### ISSUE TITLE
KIA Sorento (Diesel -- kein PHEV !) - Cannot read property 'reservChargeInfos' of undefined

### ISSUE THREAD

**Issue by stbuerger** [Newan/ioBroker.bluelink#14]
Adapter (1.0.4) funktioniert soweit fast prima.
- login geht
- daten kommen auch korrekt rein 
  ... debug: bluelink.0 (15087) {"vehicleStatus":{"airCtrlOn":false,"engine":false,"doorLock":true,"doorOpen":  
  ..... "battery":{"batSoc":78,"batState":0,"sjbDeliveryMode":1,"batSignalReferenceValue": 
  ..... "fuelLevel":25, ... ,"time":"20210614185629"},"odometer":{"value":7751.1,"unit":1}}
- dann aber 
  ... error: bluelink.0 (15087) Error on API-Request GetFullStatus
  ... debug: bluelink.0 (15087) Cannot read property 'reservChargeInfos' of undefined

debug der bluelinky lib mit "npm run debug" funktioniert komplett !

What's the matter ???

**Comment by Newan** [comment]
Diesel nicht getestet und keine Daten. Da ich die Elektrowerte vorausgesetzt habe, wird nicht geprüft ob es die Objekteigenschaft gibt. Bitte einmal mit debug abfragen und den debug log hier posten (Passwörter und fin etc entfernen!!)

**Comment by stbuerger** [comment]
>>> ".. mit debug abfragen .."
heisst für IOB noobs: "Adapter/Instance -> Spalte "loglevel" = "debug" ??? Oder geht da noch mehr ???

**Comment by stbuerger** [comment]
SOWAS hier (?)

bluelink.0 | 2021-07-05 23:54:16.218 | debug | (20724) system.adapter.admin.0: logging true
-- | -- | -- | --
bluelink.0 | 2021-07-05 23:53:36.936 | debug | (20724) Cannot read property 'reservChargeInfos' of undefined
bluelink.0 | 2021-07-05 23:53:36.935 | error | (20724) Error on API-Request GetFullStatus
bluelink.0 | 2021-07-05 23:53:36.927 | debug | (20724) {"vehicleStatus":{"airCtrlOn":false,"engine":false,"doorLock":true,"doorOpen":{"frontLeft":0,"frontRight":0,"backLeft":0,"backRight":0},"trunkOpen":false,"airTemp":{"value":"01H","unit":0,"hv
bluelink.0 | 2021-07-05 23:53:36.927 | info | (20724) Set new status
bluelink.0 | 2021-07-05 23:53:22.613 | info | (20724) Read new status from api
bluelink.0 | 2021-07-05 23:53:22.600 | info | (20724) Vehicles found
bluelink.0 | 2021-07-05 23:53:19.039 | debug | (20724) system.adapter.admin.0: logging false
bluelink.0 | 2021-07-05 23:53:18.518 | debug | (20724) {"username":"__USERNAME__","password":"__PWD__","pin":"__PIN__","brand":"kia","vin":"__VIN__","region":"EU"}
bluelink.0 | 2021-07-05 23:53:18.517 | info | (20724) Login to api
bluelink.0 | 2021-07-05 23:53:18.499 | info | (20724) starting. Version 1.0.4 in /opt/iobroker/node_modules/iobroker.bluelink, node: v12.22.1, js-controller: 3.2.16
bluelink.0 | 2021-07-05 23:53:18.400 | debug | (20724) statesDB connected
bluelink.0 | 2021-07-05 23:53:18.399 | debug | (20724) States connected to redis: 127.0.0.1:9000
bluelink.0 | 2021-07-05 23:53:18.396 | debug | (20724) States create User PubSub Client
bluelink.0 | 2021-07-05 23:53:18.395 | debug | (20724) States create System PubSub Client
bluelink.0 | 2021-07-05 23:53:18.392 | debug | (20724) Redis States: Use Redis connection: 127.0.0.1:9000
bluelink.0 | 2021-07-05 23:53:18.391 | debug | (20724) objectDB connected
bluelink.0 | 2021-07-05 23:53:18.387 | debug | (20724) Objects connected to redis: 127.0.0.1:9001
bluelink.0 | 2021-07-05 23:53:18.375 | debug | (20724) Objects client initialize lua scripts
bluelink.0 | 2021-07-05 23:53:18.375 | debug | (20724) Objects create User PubSub Client
bluelink.0 | 2021-07-05 23:53:18.374 | debug | (20724) Objects create System PubSub Client
bluelink.0 | 2021-07-05 23:53:18.373 | debug | (20724) Objects client ready ... initialize now
bluelink.0 | 2021-07-05 23:53:18.331 | debug | (20724) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.iobtest0 | 2021-07-05 23:53:17.704 | info | instance system.adapter.bluelink.0 started with pid 20724

**Comment by Newan** [comment]
Genau, aber lade den log ml herunter, den Teil:

20724) {"vehicleStatus":{"airCtrlOn":false,"engine":false,"doorLock":true,"doorOpen":{"frontLeft":0,"frontRight":0,"backLeft":0,"backRight":0},"trunkOpen":false,"airTemp":{"value":"01H","unit":0,"hv

brauch ich komplett!

**Comment by Newan** [comment]
für den error gibt es ein fix in 1.0.7

**Comment by stbuerger** [comment]
Werde 1.0.7 dann morgen mal testen.
Hier aber noch*mal  einen aktuellen Log .. 
[LOG.TXT](https://github.com/Newan/ioBroker.bluelink/files/6772590/LOG.TXT)

**Comment by stbuerger** [comment]
OK .. werde 1.0.7 dann morgen mal testen

Hier noch'mal einen aktuellen LOG 
[LOG.TXT](https://github.com/Newan/ioBroker.bluelink/files/6772614/LOG.TXT)

**Comment by stbuerger** [comment]
SO .. tested 1.0.7: Fehler ändert sich zu

2021-07-06 22:28:51.381  - [31merror[39m: bluelink.0 (13006) Error on API-Request GetFullStatus
2021-07-06 22:28:51.381  - [34mdebug[39m: bluelink.0 (13006) Cannot read property 'drvDistance' of undefined
[LOG.TXT](https://github.com/Newan/ioBroker.bluelink/files/6772728/LOG.TXT)

**Comment by Newan** [comment]
Update in 1.0.8

**Comment by stbuerger** [comment]
Thx for the great work and latest update  ... unfortunately my test with 1.0.8 now bumps with ..

```
- error: bluelink.0 (9196) Error on API-Request GetFullStatus
- debug: bluelink.0 (9196) Cannot read property 'coord' of undefined
```

Maybe there is a more general way of dealing with "undefined" ?
[20210730sb000_BLOG.txt](https://github.com/Newan/ioBroker.bluelink/files/6907350/20210730sb000_BLOG.txt)

**Comment by Newan** [comment]
check 1.0.9 pls

**Comment by stbuerger** [comment]
Good Job !
No errors with 1.0.9 - not sure whether commands (un-/lock) and all/most parameters work correct.
I'll follow up with more details and logs once new version has been running for a while.

**Comment by stbuerger** [comment]
OK - here we go ..
Adapter version: 1.0.9, Car: KIA Sorento MQ4 (Build 2020) DIESEL
* Adapter installs without error, Instance is running without errors
* gets "some" but only few data
-- bluelink.0.odometer: DATA OK
-- bluelink.0.vehicleLocation: NO DATA -- obvious according to code (change) in 1.0.9
-- bluelink.0.vehicleStatus.battery.soc-12V: OK
-- bluelink.0.vehicleStatus.dte: NO DATA
ALL THIS data can correctly be retrieved with a) NODE-RED BLUELINKY or b) debug.ts script from https://github.com/Hacksore/bluelinky

Adapter debug log:
[20210801IOBLOG.txt](https://github.com/Newan/ioBroker.bluelink/files/6919772/20210801IOBLOG.txt)

**Comment by Newan** [comment]
Also in der Debugausgabe sehe ich keine Koordinaten, bitte prüfe nochmal ob die wirklich aus dem debug.ts kommen und sende mal die Ausgabe. DTE habe ich gefunden kommt in 1.1.0

**Comment by stbuerger** [comment]
Ausgaben von "npm run debug" (latest version @ https://github.com/Hacksore/bluelinky)
Bei Eingabe/Auswahl von "locate" bekomme ich:

__? What you wanna do? locate
[2021-10-11 13:14:45] debug: Token not expired, no need to refresh
locate : {
  "latitude": 50.069389,
  "longitude": 8.2624,
  "altitude": 3,
  "speed": {
    "unit": 0,
    "value": 0
  },
  "heading": 110
}__

see "locate" in full attached log
[20211011debug.txt](https://github.com/Newan/ioBroker.bluelink/files/7322039/20211011debug.txt)

**Comment by Newan** [comment]
no response
