### ISSUE TITLE
Warning: npm request package is deprecated

### ISSUE THREAD

**Issue by meistermopper** [Newan/ioBroker.bluelink#143]
js-controller: 5.0.19
NPM: 10.5.2
nodejas: 20.13.1
Adapter: v2.3.6 

It seems like the npm request package is deprecated. Whenever I call up the vehicle data with a blockly, I get a warning in the log.

```
javascript.0	2024-05-26 08:59:00.215	warn	script.js.smarthome.Kia.Datenabfrage: request package is deprecated - please use httpGet (or a stable lib like axios) instead!
javascript.0	2024-05-26 08:59:00.232	warn	script.js.smarthome.Kia.Datenabfrage: request blockly block is deprecated - please use "http (GET)" instead
```

After a consideration I have no idea at all whether this issue is better placed with the javascript adapter?

**Comment by arteck** [comment]
`javascript.0`

 its not bluelink adapter message
