### ISSUE TITLE
@EuropeVehicle.status: [503] Service Unavailable

### ISSUE THREAD

**Issue by daOlli** [Newan/ioBroker.bluelink#152]
I am getting lately the following Error:

@EuropeVehicle.status: [503] Service Unavailable on [GET] https://prd.eu-ccapi.kia.com:8080/api/v2/spa/vehicles/34... ...25/status - {"retCode":"F","resCode":"5031","resMsg":"Unavailable remote control - Service Temporary Unavailable","msgId":"0d... ...19"}

Following with a restart of the Adapter

**Comment by Ilovegym66** [comment]
The Error have nothing to do with the iobroker Adapter. Read the error msg again, please. :)
