### ISSUE TITLE
Add car id / year of manfacture to the batterie warning

### ISSUE THREAD

**Issue by Patrick-Walther** [Newan/ioBroker.bluelink#163]
hi,

can you add the car ID or the year of manufacture to the battery status warning

thanks

Regards
patrick

**Comment by arteck** [comment]
can you see this information in the app ??

**Comment by Patrick-Walther** [comment]
No, but in the objects you add the object "BatteryControlState12V" (See your wiki entry), so i think it is possible to add this in the warning. If it not possible please close this point.

**Comment by arteck** [comment]
ahh if you have more cars you see now only the warning but not from which car is it... right ?

**Comment by Patrick-Walther** [comment]
sorry, yes i have two cars, if forgot this informartion. The warning don't say which car or id is it.

**Comment by arteck** [comment]
vin is added... check GIT version

**Comment by Patrick-Walther** [comment]
Thanks for the Update, i can Check it monday next week.
