### ISSUE TITLE
Anfragen überschreiten das Limit trotz Begrenzung

### ISSUE THREAD

**Issue by ali86x** [Newan/ioBroker.bluelink#171]
Auszug aus dem Log:
2024-11-01 19:27:08.884 - error: bluelink.0 (1387) ManagedBluelinkyError: @EuropeController.getVehicles: [509] status code 509 on [GET] https://prd.eu-ccapi.kia.com:8080/api/v1/spa/vehicles - {"retCode":"F","resCode":"5091","resMsg":"Exceeds number of requests - Exceeds Number of Requests.","msgId":"e77bdb90-987e-11ef-8d98-b77fecf79cce"}
2024-11-01 19:27:08.885 - error: bluelink.0 (1387) Server is not available or login credentials are wrong
2024-11-01 19:27:08.885 - error: bluelink.0 (1387) next auto login attempt in 1 hour or restart adapter manual

Limit ist im Adapter auf 24 pro Tag eingestellt. 
![Screenshot_20241101-202500](https://github.com/user-attachments/assets/499fa55c-0cc7-443a-ae81-ece780bc096c)

Aber bereits früh am Morgen wird das Limit überschritten.
Sogar die App wird dann gesperrt. 
![Screenshot_20241101-202914](https://github.com/user-attachments/assets/dbc79875-2b78-4b26-8096-cc37f4e9fb59)

Wie lässt sich das eingrenzen? 
Macht so leider keinen Sinn, wenn der Adapter mir den Zugang zerschießt.

Adapter Version 2.3.6

**Comment by Ilovegym66** [comment]
Sicher, dass kein Script läuft oder etwas anderes darauf zu greift?

**Comment by ali86x** [comment]
Ich habe ein Script, welches alle 30 Minuten den Status aktualisiert ("Force Update"). Mehr nicht. 
Aber selbst damit komme ich ja auf maximal 48 anfragen pro Tag. 
Also immer noch nicht genug um die Sperre auszulösen

**Comment by Ilovegym66** [comment]
Mach doch bitte im Forum dazu ein Thread auf, ich denke nicht, dass es am Adapter liegt. Um das nachvollziehen zu koennen, braucht man mehr Angaben, das gehoert nicht hierher.

**Comment by ali86x** [comment]
Kann ich gerne machen. 
Aber sorry, für mich gehört das genau hier hin. 
Dafür sind Issues gedacht. Um Störungen oder Probleme in Verbindung mit einem Adapter darzustellen. 
Wenn weitere Informationen benötigt werden, kann ich die gerne zur Verfügung stellen. 
Ich sehe keine weiteren äußeren Einflüsse oder Probleme, die zu dem Fehler führen. 

Ich habe eine Vermutung:
Oftmals zickt ja der Server von Kia mal rum. Kann es sein, dass der Adapter dann mehrfach Anfragen stellt, die dann das Limit überschreiten?

**Comment by ali86x** [comment]
Forum:
https://forum.iobroker.net/topic/77808/bluelink-anfragen-%C3%BCberschreiten-limit-sperrung

**Comment by Ilovegym66** [comment]
tritt der Fehler noch auf?

**Comment by ali86x** [comment]
> tritt der Fehler noch auf?

Ja immer wieder. 
Hab die Instanz jetzt n paar Tage gestoppt, damit ich zumindest vom Handy den Fernzugriff habe. Aber sobald ich die Instanz starte, dauert es nicht lange und das Limit wird überschritten

**Comment by ali86x** [comment]
Habe die Instanz jetzt mal wieder gestartet und bekomme folgende Fehlermeldung:
@EuropeVehicle.status: [400] Bad Request on [GET] https://prd.eu-ccapi.kia.com:8080/api/v2/spa/vehicles/ce9012cb-b1ae-4d48-8215-4f33f8b57e5d/status - {"retCode":"F","resCode":"4004","resMsg":"Duplicate request - Duplicate request","msgId":"fcd41840-9d1f-11ef-8d98-a5715383720b"}

**Comment by ali86x** [comment]
Adapter um 16.50 Uhr gestartet und um 20.10 Uhr Limit erreicht. Da kann doch was nicht stimmen. 
Was für Infos können weiter helfen?

**Comment by Ilovegym66** [comment]
siehe Forum, ohne die ganzen Infos kann HIER keiner helfen.

**Comment by ali86x** [comment]
Neuinstallation des Adapters hat das Problem behoben.
