### ISSUE TITLE
vehicleStatus.battery.plugin has wrong datatype

### ISSUE THREAD

**Issue by dklinger** [Newan/ioBroker.bluelink#18]
**Describe the bug**  
Log shows "State value to set for "bluelink.0.vehicleStatus.battery.plugin" has to be type "boolean" but received type "number""

**To Reproduce**  
Connect car, trigger/wait for a sync und look into the ioBroker log.

**Expected behavior**  
State has to be of type number, not boolean.

**Comment by Newan** [comment]
Thanks for PR. Check it soon

**Comment by Newan** [comment]
merged
