### ISSUE TITLE
Pulldown-Menü geht nicht

### ISSUE THREAD

**Issue by Michaelnorge** [Newan/ioBroker.bluelink#2]
Hallo.
Bei den Einstellungen des Adapters steht KIA, Hyundai kann nicht mehr ausgewählt werden.
![image](https://user-images.githubusercontent.com/42386692/112726008-65d0be00-8f1b-11eb-8bf4-bd5a6ad80177.png)

**Comment by Newan** [comment]
Hast du ein Hyundai Fahrzeug?
