### ISSUE TITLE
Bluelink smartphone app constantly changes language to english

### ISSUE THREAD

**Issue by dklinger** [Newan/ioBroker.bluelink#20]
My Bluelink app on my smartphone is constantly changing it's language from german to english since I'm using this ioBroker adapter.
I think this is coincidence but wanted to clarify if this is based on the adapter?

**Comment by Newan** [comment]
I set only this options:

`const tmpConfig = {
                username: this.config.username,
                password: this.config.client_secret,
                pin: this.config.client_secret_pin,
                brand: this.config.brand,
                vin: this.config.vin,
                region: 'EU' //set over GUI next time
            };`

Ich weiß nicht, worum der das ändert, sorry. Sie können das Debug-Skript überprüfen, ob er es auch ändert: https://github.com/Hacksore/bluelinky

**Comment by Newan** [comment]
no response
