### ISSUE TITLE
Wrong Credentials; maybe restrictions to password?

### ISSUE THREAD

**Issue by meistermopper** [Newan/ioBroker.bluelink#22]
When I start the adapter, I get the following error message:

<html><body>

bluelink.0 | 2021-10-14 17:43:01.958 | error | ManagedBluelinkyError:  @EuropeController.login: [400] Bad Request on [POST]  https://prd.eu-ccapi.kia.com:8080/api/v1/user/signin -  {"errId":"e2253e03-ae98-41bd-9360-e1d1cc0e7236","errCode":"4003","errMsg":"Invalid  values"}
-- | -- | -- | --

</body>
</html>

I'm shure that i insertet the right vin.

Could it be because the password cannot contain any special characters?
I would not like to deviate from my principle of uppercase, lowercase, numbers and special characters (a total of 12 characters).

There are no problems with the Android app.

Adapter version: 1.0.7
js-controller: 3.3.18
nodejs: 14.18.1
npm: 6.14.15

**Comment by Jens-Schmerenko** [comment]
I have the same Problem with Hyundai ioniq 5 :
ManagedBluelinkyError: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin - {"errId":"06709374-5255-4e12-889c-ac1e0a41d4e5","errCode":"4003","errMsg":"Invalid values"}

Adapter 1.11
NPM 6.14.15
Node.js v14.18.0

**Comment by Newan** [comment]
relogin in the app to resolve this
