### ISSUE TITLE
Falsche Fahrzeug wird ausgelesen

### ISSUE THREAD

**Issue by thoeckerde** [Newan/ioBroker.bluelink#30]
Wenn man in der KIA UVO-App 2 Fahrzeuge registriert hat, werden im ioBroker immer die Daten vom zuletzt registrierten Fahrzeug geladen. Egal Welche VIN in der Konfiguration gespeichert ist.

**Comment by Newan** [comment]
Hast du die 2.x getestet?

**Comment by thoeckerde** [comment]
Natürlich.... nicht! :( Im Broker wurde mir kein Update angezeigt. Habe es jetzt namuell geupdatet. Geht! Beim erstenmal erst alles richtig lesen, verstehen, dann Fehler melden. Sorry :)
