### ISSUE TITLE
Convert Kia-Temperature values to celcius degree

### ISSUE THREAD

**Issue by teejay-81** [Newan/ioBroker.bluelink#34]
Is it possible to manage the conversion of the KIA hex-temperature values to celcius degrees?

I found a code snippet from bluelinky that handles with this (and the date/time conversion):

"import { REGION } from './constants';

const dec2hexString = (dec: number) => '0x' + dec.toString(16).substr(-4).toUpperCase();

const floatRange = (start, stop, step) => {
  const ranges: Array<number> = [];
  for (let i = start; i <= stop; i += step) {
    ranges.push(i);
  }
  return ranges;
};

const REGION_STEP_RANGES = {
  EU: {
    start: 14,
    end: 30,
    step: 0.5,
  },
  CA: {
    start: 16,
    end: 32,
    step: 0.5,
  }
};

// Converts Kia's stupid temp codes to celsius
// From what I can tell it uses a hex index on a list of temperatures starting at 14c ending at 30c with an added H on the end,
// I'm thinking it has to do with Heat/Cool H/C but needs to be tested, while the car is off, it defaults to 01H
export const celciusToTempCode = (region: REGION, temperature: number): string => {
  // create a range of floats
  const { start, end, step } = REGION_STEP_RANGES[region];
  const tempRange = floatRange(start, end, step);

  // get the index from the celcious degre
  const tempCodeIndex = tempRange.indexOf(temperature);

  // convert to hex
  const hexCode = dec2hexString(tempCodeIndex);

  // get the second param and stick an H on the end?
  // this needs more testing I guess :P
  return `${hexCode.split('x')[1].toUpperCase()}H`.padStart(3, '0');
};

export const tempCodeToCelsius = (region: REGION, code: string): number => { 
  // create a range
  const { start, end, step } = REGION_STEP_RANGES[region];
  const tempRange = floatRange(start, end, step);

  // get the index
  const tempIndex = parseInt(code, 16);

  // return the relevant celsius temp
  return tempRange[tempIndex];
};

/**
 * Parses an API date string
 * @param str the date in yyyyMMdd or yyyyMMddHHmmss format
 * @returns The parsed date
 */
export const parseDate = (str: string): Date => {
	const year = parseInt(str.substring(0, 4));
	const month = parseInt(str.substring(4, 6));
	const day = parseInt(str.substring(6, 8));
  if (str.length <= 8) {
    return new Date(year, month - 1, day);
  }
	const hour = parseInt(str.substring(8, 10));
	const minute = parseInt(str.substring(10, 12));
	const second = parseInt(str.substring(12, 14));
	return new Date(year, month - 1, day, hour, minute, second);
};

const MILISECONDS_PER_SECOND = 1000;
const MILISECONDS_PER_MINUTE = MILISECONDS_PER_SECOND * 60;

/**
 * Adds a certain amount of minutes to a date
 * @param date The date to adds minutes to
 * @param minutes The number of minutes to add
 * @returns The updated date
 */
export const addMinutes = (date: Date, minutes: number): Date => {
  return new Date(date.getTime() + (minutes * MILISECONDS_PER_MINUTE));
};"

**Comment by Newan** [comment]
Which object is missing the conversion?

**Comment by teejay-81** [comment]
> Which object is missing the conversion?

vehicleStatusRaw - vehicleStatus - airTemp - value

**Comment by Newan** [comment]
vehicleStatusRaw = raw data :-)
But we can add the object under status and then transform it

**Comment by Newan** [comment]
Please test last commit, thanks

**Comment by Ilovegym66** [comment]
thank you, works fine. One thing, the object was created as boolean, I changed it to number and add unit C to it.

**Comment by Newan** [comment]
> thank you, works fine. One thing, the object was created as boolean, I changed it to number and add unit C to it.

Ist was late 😅. Thanks comes in the next release

**Comment by klausiob** [comment]
Is this solution also for Hyundai cars?
I have an IONIQ 5. The actual entry is:
"airTemp":{"value":"02H","unit":0,"hvacTempType":1},

**Comment by Newan** [comment]
Bei der Temperaturberechnung wird nicht unterschieden. Welche Adapterversion setzt du ein @klausiob

**Comment by klausiob** [comment]
V 2,1,2

**Comment by Newan** [comment]
Ok 2.2.0 installieren über Expertenmodus und github oder auf nächste stable warten

**Comment by klausiob** [comment]
OK, bleiben da Daten und Objekte erhalten? Welche Temperatur und wo zeigt er dann eine an?
Übrigens einen 500er-Fehler hatte ich noch nie.

**Comment by Newan** [comment]
Ja bleibt kommen ggf neue dazu

**Comment by klausiob** [comment]
OK danke erstmal, habe jetzt die 2.2.1. und habe jetzt im VehicleStatus airTemp=15 (Vehicle air temper**e**ature). Was ist das für eine Temperatur? Die App zeigt als Außentemperatur 3°C. 
Nur nochmal zum Verständnis: vehicleStatusRaw ist die Original-Response von dem Request "Full status" und vehicleStatus sind die vom Adapter aufbereiteten Daten. Woher kommen dann die Daten für driveHistory, monthlyReport und tripInfo?
