### ISSUE TITLE
Put charge limit to control

### ISSUE THREAD

**Issue by meistermopper** [Newan/ioBroker.bluelink#35]
Hello everyone, I would be very happy if the loading target can also be controlled so that it can be set without an app.

Is that possible?

Best regards
Thomas

**Comment by Newan** [comment]
Please change the object 'vehicleStatus.battery.charge_limit_slow' or 'vehicleStatus.battery.charge_limit_fast'
If the Objects not writeable, delete the objects and restart the adapter. this recreate the objects.

**Comment by meistermopper** [comment]
I did, but unfortunately it did nothing.

The data points are writable.

**Comment by Newan** [comment]
Please ask in the Forum if someone else have also this problem.

**Comment by torsten3009** [comment]
some to me as mentioned in https://forum.iobroker.net/topic/43592/adapter-hyundai-bluelink-oder-kia-uvo/487

**Comment by arteck** [comment]
done
