### ISSUE TITLE
Change debug log level with restart

### ISSUE THREAD

**Issue by meistermopper** [Newan/ioBroker.bluelink#36]
Every time the adapter is restarted, the loglevel is set to debug, although it was previously set to error.

**Comment by Newan** [comment]
Welche Admin Version? Kann das so nicht nachstellen

**Comment by meistermopper** [comment]
Admin 5.2.3 - soeben nochmal getestet. Loglevel error -> Adapter gestoppt und neu gestartet -> loglevel debug
