### ISSUE TITLE
API Service Unavailable

### ISSUE THREAD

**Issue by Michaelnorge** [Newan/ioBroker.bluelink#38]
Hat Hyundai an seinen Seiten geschraubt?

In den letzten Tagen kam die Fehlermeldung "Temporary Unavailable", seit heute steht im Log "Service Unavailable"

Kann das mal jemand bestätigen?

Grüße
Michael

> 2021-12-30 20:01:54.337  - error: bluelink.0 (28143) Error on API-Request GetFullStatus
--
2021-12-30 20:01:54.338  - error:  bluelink.0 (28143) @EuropeVehicle.fullStatus: [503] Service Unavailable  on [GET]  https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/location  - {"retCode":"F","

**Comment by Ilovegym66** [comment]
Ja der Fehler war bei mir, ist inzwischen wieder weg, dafür hab ich mehr datenpunkte …

**Comment by Michaelnorge** [comment]
Ok habs selber gefixt. Neulich kam Post vonn Hyundai. 

Laut Papiere ist meine Frau der Halter, bis dato war das aber ich in der App. 
Neulich kam Post von Hyundai. 
Die wollten eine Verzifizierug des Halters inkl. Ausweiskopie und Kaufbeleg des Autos, daher wurde mein Account wohl geblockt beim ioBroker-Adapter. Bin nun mit den Einlogdaten meiner Frau angemeldet und der Adapter funktioniert wieder!
