### ISSUE TITLE
Service Temporary Unavailable

### ISSUE THREAD

**Issue by Michaelnorge** [Newan/ioBroker.bluelink#39]
Bei #38 zu früh gefreut, es hat gestern funktioniert und nun wieder ein Fehler im log:

@EuropeVehicle.fullStatus: [503] Service Unavailable on [GET] https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/location - {"retCode":"F","resCode":"5031","resMsg":"Unavailable remote control - Service Temporary Unavailable","msgId":"4a28413d-4f87-4ef6-b6ba-ed3534417ba9"}

So hat das beim letzten Mal auch angefangen. Danach kam der Fehler " #38  "

**Comment by Michaelnorge** [comment]
Hab den Adapter mal koplett runtergeschmissen vom System und neu aufgesetzt, jetzt kommt folgende Fehlermeldung: 
`
2022-01-02 13:25:04.987  - error:  bluelink.0 (16221) ManagedBluelinkyError: @EuropeController.login:  [400] Bad Request on [POST]  https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin -  {"errId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxx","errCode":"4003","errMsg":"Invalid  values"}`

Werde dem Ratschlag der App "Please logout in the app and relogin in the app" gleich mal folge leisten und hier berichten....

**Comment by Michaelnorge** [comment]
Ergänzung: Keinerlei Besserung, Fehler immer noch vorhanden. Zur Zeit ist der Adapter leider für mich unbrauchbar:
`2022-01-02 13:32:39.252  - error: bluelink.0 (17841) Error on API-Request GetFullStatus
--
2022-01-02 13:32:39.254  - error:  bluelink.0 (17841) @EuropeVehicle.fullStatus: [503] Service Unavailable  on [GET]  https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/9306e6d9-b02e-xxxx-a51e-xxxxxxxxxxe/location  - {"retCode":"F","resCode":"5031","resMsg":"Unavailable remote control -  Service Temporary  Unavailable","msgId":"xxxxxxxx-aabe-xxxx-8c4a-xxxxxxxxxa8a"}`

**Comment by luebke01** [comment]
![grafik](https://user-images.githubusercontent.com/80831456/148508892-ceb8466f-3fc5-4c6d-9901-c8e3c9675f02.png)
Bei mir ist das gleiche Fehlerbild. Es gibt immer wieder mal ein Moment, da kommt die Abfrage durch, aber das ist gefühlt 1x die Woche von 3 Abfragen täglich.

**Comment by Newan** [comment]
Bitte mal Prüfen ob das Auto in einen "Sleep" Mode geht. Das sieht ja ganz so aus. Da es so viele unterschiedliche Fahrzeuge gibt können wir von außen nichts machen. Alle 500er Fehler sind Serverfehler bei Hyndai.

**Comment by luebke01** [comment]
Ich habe eben mal etwas nach dem Fehler gesucht. Hier ist der identische Fehler:
https://gitmemory.cn/repo/Hacksore/bluelinky/issues/183
Und auch bei mir ist es so, dass ich zwar die allgemeinen Daten (Ladestatus/km-Werte/Türstatis/...) in der KIA UVO App abfragen kann, aber die Locationinfos können in der UVO-App nicht abgefragt werden.
![grafik](https://user-images.githubusercontent.com/80831456/148525627-b9f526cd-b5b2-4897-8918-f5aac59aa98d.png)
Daher vermute ich, dass eine Abfrage ohne die Locationinfos über den Adapter vermutlich funktionieren würde.  Da es im verlinktem Beitrag um die Softwareversion des Infotainmentsystems ging, auch ich habe das November Update (bei KIA vom 17.11.21) aufgespielt. Sollte es also ein neues "Feature" der November Version sein, müssten ja bald mehr solche Fehler auftauchen.

**Comment by Michaelnorge** [comment]
@luebke01 Nur aus Neugierde: Befindest Du Dich in Deutschland bzw. ist dein Auto in Deutschland angemeldet?

**Comment by luebke01** [comment]
@Michaelnorge Ja, ich bin aus Deutschland. Die App habe ich nur auf Englisch gelassen, da sie (zumindest früher) bei mir immer wieder mal nach einer Bluelink-Abfrage auf Englisch gestellt wurde und der Adapter erst wieder funktionierte, wenn ich das in der App bestätigt habe. 
@Newan 
Ich vermute ja das November Update als Auslöser unserer Probleme. Lt. dem von mir oben verlinkten Beitrag hat der Kommentator wohl eine Teilabfrage (ohne Location) gemacht, wenn der Full Status Update fehlschlägt ("I implemented now a workarround and request the status w/o position if the full status update fails.") Wäre super, wenn es diese Möglichkeit auch im Bluelink-Adapter gibt.

**Comment by Newan** [comment]
Habe derzeit keinen Acoount um dies zu testen, könnte mir einer seinen für Testzwecke zur Verfügung stellen: info@newan.de Schaue dann gerne dabei

**Comment by Newan** [comment]
So also, wenn ich bei einem Fullstatus den 503 bekomme, heiß das nur das der die Location nicht findet. Ich kann dann aber nur einen minimal Staus abfragen der bei Kia folgendes herausgibt:

```
{
    "chassis":{
       "hoodOpen":false,
       "trunkOpen":false,
       "locked":false,
       "openDoors":{
          "frontRight":false,
          "frontLeft":false,
          "backLeft":false,
          "backRight":false
       },
       "tirePressureWarningLamp":{
          "rearLeft":false,
          "frontLeft":false,
          "frontRight":false,
          "rearRight":false,
          "all":false
       }
    },
    "climate":{
       "active":false,
       "steeringwheelHeat":false,
       "sideMirrorHeat":false,
       "rearWindowHeat":false,
       "defrost":false,
       "temperatureSetpoint":14,
       "temperatureUnit":0
    },
    "engine":{
       "ignition":false,
       "accessory":false,
       "rangeGas":338,
       "range":393,
       "rangeEV":0,
       "plugedTo":0,
       "charging":false,
       "estimatedCurrentChargeDuration":1,
       "estimatedPortableChargeDuration":9,
       "estimatedStationChargeDuration":6,
       "batteryCharge12v":73,
       "batteryChargeHV":97
    },
    "lastupdate":"2022-01-10T16:46:55.000Z"
 }
```
Ich hab ein Testrelease gemacht. Wenn die Fullabfrage schief läuft macht er automatisch eine minimal Abfrage.
Schaut mal ob euer Minimalstatus bei anderen Herstellern anders aussieht. Seht ihr im Debuglog

**Comment by luebke01** [comment]
Hallo Newan,
ich habe den Adapter aktualisiert und der small status wird ausgeführt.
![grafik](https://user-images.githubusercontent.com/80831456/148900928-052249be-eb74-4348-8779-65a12df163c0.png)
Der SOC wird aktualisiert, die Kilometer Werte werden jedoch nicht in iobroker geschrieben
![grafik](https://user-images.githubusercontent.com/80831456/148901014-b5cf309e-2832-4cde-a23c-1a4330a74a74.png)
Gibt es noch eine Chance mit dem small status an den "odometer" ranzukommen?

**Comment by Newan** [comment]
Ja Stück für Stück. Erstmal prüfen ob der small läuft. Dann erweitern wir um Datenpunkte und weitere Anfragen

**Comment by klausiob** [comment]
Ich habe heute zum ersten Mal den Error on API-Full-Status - Fallback GetNormalStatus bekommen.  Hier das JSON für einen IONIQ5
```json
{
    "chassis": {
        "hoodOpen": false,
        "trunkOpen": false,
        "locked": true,
        "openDoors": {
            "frontRight": false,
            "frontLeft": false,
            "backLeft": false,
            "backRight": false
        },
        "tirePressureWarningLamp": {
            "rearLeft": false,
            "frontLeft": false,
            "frontRight": false,
            "rearRight": false,
            "all": false
        }
    },
    "climate": {
        "active": false,
        "steeringwheelHeat": false,
        "sideMirrorHeat": false,
        "rearWindowHeat": false,
        "defrost": false,
        "temperatureSetpoint": 15,
        "temperatureUnit": 0
    },
    "engine": {
        "ignition": false,
        "accessory": false,
        "range": 142,
        "rangeEV": 142,
        "plugedTo": 0,
        "charging": false,
        "estimatedCurrentChargeDuration": 125,
        "estimatedFastChargeDuration": 44,
        "estimatedPortableChargeDuration": 1090,
        "estimatedStationChargeDuration": 255,
        "batteryCharge12v": 86,
        "batteryChargeHV": 39
    },
    "lastupdate": "2022-02-14T05:41:37.000Z"
}
```
Zu den Durations, würde ich sagen, ist die Dauer in Minuten. 
Da ich Ziele für AC und DC auf 100% gestellt habe und aktuell bei 39% liege
Notladekabel 1090:60=ca. 18h
DC-Lader: 44min
AC-Lader (11kWh): 4,25h -> macht 46,75 kWh
39% von 72kWh-Akku macht 28 kWh -> Summe: ca. 75 kWh
Zeitschätzung evtl. noch außentemperaturabhängig, und dass er am Ende bis 100% nur noch mit 3-7kWh lädt.
