### ISSUE TITLE
History Today/now

### ISSUE THREAD

**Issue by lindi200000** [Newan/ioBroker.bluelink#46]
Hallo,
ich habe heute den Adapter im Stable das erste mal für einen KIA Ceed SW installiert (Kein E-Fahrzeug).
Was mir gleich auffällt, ist es möglich in der History oder auch wo anders ein "Today" hinzuzufügen?
So das man immer die Tagesaktuellen Daten per z.B. Influx oder dergleichen loggen kann?
Aktuell scheint es das so nicht zu geben, sondern nur mit dem aktuellen Datum. Das erlaubt aber leider nicht das durchgehende loggen.

VG
Marcus

**Comment by Newan** [comment]
Könntest du dazu ein Beispiel machen? Alle Daten siehst du im debuglog welche zur Verfügung stehen.

**Comment by lindi200000** [comment]
![Screenshot_20220406-211445](https://user-images.githubusercontent.com/16406425/162051468-7325cb9a-e29b-4849-a18f-389e69a3b121.jpg)
Aktuell gibt es im history für jeden Tag einen Datenpunkt. Es währe super, wenn der aktuelle Tag mit today oder current extra noch gibt. 0 Uhr wird dann für den dp automatisch der neue Tag genommen, also so wie wenn ein neuer Tag im der Ordner Struktur erstellt wird und es beginnt wieder von vorn.
Dadurch kann man das alles in influx loggen und es können Auswertungen gemacht werden.

Dadurch das derzeit immer ein neuer Ordner mit neuen Namen erstellt wird, kann man das leider nicht loggen.

**Comment by arteck** [comment]
erledigt..
immer um 23 uhr wird der neue Datenpunkt today aktualisisert
man kann den auch selber triggern über control->force_checkDirveInfo
