### ISSUE TITLE
API-Request GetFullStatus  Adapter:v2.2.0

### ISSUE THREAD

**Issue by lindi200000** [Newan/ioBroker.bluelink#47]
Hallo,
ich habe einen KIA Ceed SW (kein E-Fahrzeug) und bekomme folgenden Fehler beim Abrufen der Daten:
`Cannot read property 'coord' of undefined`
`error | Error on API-Request GetFullStatus`

Debug gibt folgendes aus:

`{"vehicleStatus":{"airCtrlOn":false,"engine":false,"doorLock":true,"doorOpen":{"frontLeft":0,"frontRight":0,"backLeft":0,"backRight":0},"trunkOpen":false,"airTemp":{"value":"00H","unit":0,"hvacTempType":1},"defrost":false,"lowFuelLight":false,"acc":false,"hoodOpen":false,"transCond":false,"steerWheelHeat":0,"sideBackWindowHeat":0,"dte":{"value":281,"unit":1},"tirePressureLamp":{"tirePressureLampAll":0,"tirePressureLampFL":0,"tirePressureLampFR":0,"tirePressureLampRL":0,"tirePressureLampRR":0},"battery":{"batSoc":83,"batState":0},"sleepModeCheck":false,"time":"20220308171708","remoteWaitingTimeAlert":{"remoteControlAvailable":1,"remoteControlWaitingTime":168,"elapsedTime":"01:25:13"},"systemCutOffAlert":0,"tailLampStatus":0,"hazardStatus":0},"odometer":{"value":42464,"unit":1}}`

Falls weitere Infos benötigt werden, kann ich die gern nachreichen.

VG
Lindi

**Comment by Newan** [comment]
fixed next release
