### ISSUE TITLE
Warninng in 2.2.3

### ISSUE THREAD

**Issue by lindi200000** [Newan/ioBroker.bluelink#48]
Hallo,
ich habe die Version 2.2.3 nun installiert.
Folgende Meldung kommt nun in den Logs:
`
bluelink.0 | 2022-04-19 09:50:49.676 | info | undefined is not a valid state value for id "bluelink.0.U5Yxxxxxxxxxx1488.vehicleStatusRaw.vehicleLocation"
bluelink.0 | 2022-04-19 09:50:49.674 | warn | This object will not be created in future versions. Please report this to the developer.
bluelink.0 | 2022-04-19 09:50:49.673 | warn | Object bluelink.0.xxxxxxxxxxx.vehicleStatusRaw.vehicleLocation is invalid: obj.common.type has an invalid value (undefined) but has to be one of number, string, boolean, array, object, mixed, file, json
`

Viele Grüße

**Comment by Newan** [comment]
Bitte sende mal den debug log ohne sensible daten wie fin etc

**Comment by lindi200000** [comment]
`driveHistory-Data: {"cumulated":[{"period":0,"consumption":{},"distance":1096},{"period":1,"consumption":{},"distance":60.888888888888886},{"period":2,"consumption":{},"distance":38}],"history":[{"period":0,"rawDate":"20220425","date":"2022-04-24T22:00:00.000Z","consumption":{},"distance":38},{"period":0,"rawDate":"20220424","date":"2022-04-23T22:00:00.000Z","consumption":{},"distance":41},{"period":0,"rawDate":"20220423","date":"2022-04-22T22:00:00.000Z","consumption":{},"distance":46},{"period":0,"rawDate":"20220422","date":"2022-04-21T22:00:00.000Z","consumption":{},"distance":84},{"period":0,"rawDate":"20220421","date":"2022-04-20T22:00:00.000Z","consumption":{},"distance":67},{"period":0,"rawDate":"20220420","date":"2022-04-19T22:00:00.000Z","consumption":{},"distance":86},{"period":0,"rawDate":"20220419","date":"2022-04-18T22:00:00.000Z","consumption":{},"distance":108},{"period":0,"rawDate":"20220417","date":"2022-04-16T22:00:00.000Z","consumption":{},"distance":19},{"period":0,"rawDate":"20220407","date":"2022-04-06T22:00:00.000Z","consumption":{},"distance":19},{"period":0,"rawDate":"20220406","date":"2022-04-05T22:00:00.000Z","consumption":{},"distance":8},{"period":0,"rawDate":"20220405","date":"2022-04-04T22:00:00.000Z","consumption":{},"distance":50},{"period":0,"rawDate":"20220404","date":"2022-04-03T22:00:00.000Z","consumption":{},"distance":59},{"period":0,"rawDate":"20220403","date":"2022-04-02T22:00:00.000Z","consumption":{},"distance":68},{"period":0,"rawDate":"20220401","date":"2022-03-31T22:00:00.000Z","consumption":{},"distance":109},{"period":0,"rawDate":"20220331","date":"2022-03-30T22:00:00.000Z","consumption":{},"distance":87},{"period":0,"rawDate":"20220330","date":"2022-03-29T22:00:00.000Z","consumption":{},"distance":83},{"period":0,"rawDate":"20220329","date":"2022-03-28T22:00:00.000Z","consumption":{},"distance":30},{"period":0,"rawDate":"20220328","date":"2022-03-27T22:00:00.000Z","consumption":{},"distance":94},{"period":0,"rawDate":"20220327","date":"2022-03-26T23:00:00.000Z","consumption":{},"distance":47}]}`

`<html>
<body>


{"vehicleStatus":{"airCtrlOn":false,"engine":false,"doorLock":true,"doorOpen":{"frontLeft":0,"frontRight":0,"backLeft":0,"backRight":0},"trunkOpen":false,"airTemp":{"value":"00H","unit":0,"hvacTempType":1},"defrost":false,"lowFuelLight":false,"acc":false,"hoodOpen":false,"transCond":false,"steerWheelHeat":0,"sideBackWindowHeat":0,"dte":{"value":336,"unit":1},"tirePressureLamp":{"tirePressureLampAll":0,"tirePressureLampFL":0,"tirePressureLampFR":0,"tirePressureLampRL":0,"tirePressureLampRR":0},"battery":{"batSoc":62,"batState":0},"sleepModeCheck":false,"time":"20220425165534","remoteWaitingTimeAlert":{"remoteControlAvailable":1,"remoteControlWaitingTime":168,"elapsedTime":"01:47:24"},"systemCutOffAlert":0,"tailLampStatus":0,"hazardStatus":0},"odometer":{"value":44555.1,"unit":1}}
--



</body>
</html>`

Das sollte alles sein.

**Comment by Newan** [comment]
Ist der Fehler noch akut? im Debuglog sehe ich kein "vehicleStatusRaw"
