### ISSUE TITLE
Error on API-Request GetFullStatus

### ISSUE THREAD

**Issue by smokie128** [Newan/ioBroker.bluelink#49]
Hallo, ich sehe bei so gut wie jeder Abfrage solche Fehlermeldungen:

`
bluelink.0 | 2022-05-31 05:44:59.376 | error | @EuropeVehicle.fullStatus: [503] Service Unavailable on [GET] https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/xxxxxxxxxxxx/location - {"retCode":"F","resCode":"5031","resMsg":"Unavailable remote control - Service Temporary Unavailable","msgId":"ae7579ea-a25a-4e21-a3dc-xxxxxxxxxxxx"}
-- | -- | -- | --
bluelink.0 | 2022-05-31 05:44:59.375 | error | Error on API-Request GetFullStatus
bluelink.0 | 2022-05-31 01:44:32.553 | error | @EuropeVehicle.fullStatus: [503] Service Unavailable on [GET] https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/xxxxxxxxxxxx/location - {"retCode":"F","resCode":"5031","resMsg":"Unavailable remote control - Service Temporary Unavailable","msgId":"0df1f7a9-f780-4414-a705-xxxxxxxxxxxx"}
bluelink.0 | 2022-05-31 01:44:32.551 | error | Error on API-Request GetFullStatus
`

Habe deswegen auch auf 6 Abfragen pro Tag reduziert. Die meisten Datenpunkte werden weiterhin aktuell gehalten (zB. Reichweite, Location), dennoch nerven dieselben Fehlermeldungen auf Loglevel Error alle 4 Stunden etwas.

Fahrzeug ist ein Ioniq Electric FL von 2020.

**Comment by Newan** [comment]
Geht das immer noch net. Sieht nach Serverausfall aus?
