### ISSUE TITLE
Warnings in Log

### ISSUE THREAD

**Issue by SKB-CGN** [Newan/ioBroker.bluelink#50]
Hi,
i have the following warnings:

`<html><body>

bluelink.0 | 2022-06-02 14:10:13.555 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
bluelink.0 | 2022-06-02 14:10:13.555 | warn | Object  bluelink.0.xxx.driveHistory.20220601.consumption.battery  is invalid: obj.common.type has an invalid value (undefined) but has to  be one of number, string, boolean, array, object, mixed, file, json
bluelink.0 | 2022-06-02 14:10:13.554 | warn | This object will not be created in future versions. Please report this to the developer.
bluelink.0 | 2022-06-02 14:10:13.553 | warn | Object  bluelink.0.xxx.driveHistory.20220601.consumption.devices  is invalid: obj.common.type has an invalid value (undefined) but has to  be one of number, string, boolean, array, object, mixed, file, json
bluelink.0 | 2022-06-02 14:10:13.553 | warn | This object will not be created in future versions. Please report this to the developer.
bluelink.0 | 2022-06-02 14:10:13.552 | warn | Object  bluelink.0.xxx.driveHistory.20220601.consumption.climate  is invalid: obj.common.type has an invalid value (undefined) but has to  be one of number, string, boolean, array, object, mixed, file, json
bluelink.0 | 2022-06-02 14:10:13.551 | warn | This object will not be created in future versions. Please report this to the developer.
bluelink.0 | 2022-06-02 14:10:13.551 | warn | Object  bluelink.0.xxx.driveHistory.20220601.consumption.engine  is invalid: obj.common.type has an invalid value (undefined) but has to  be one of number, string, boolean, array, object, mixed, file, json
bluelink.0 | 2022-06-02 14:10:13.550 | warn | This object will not be created in future versions. Please report this to the developer.
bluelink.0 | 2022-06-02 14:10:13.550 | warn | Object  bluelink.0.xxx.driveHistory.20220601.consumption.total is  invalid: obj.common.type has an invalid value (undefined) but has to be  one of number, string, boolean, array, object, mixed, file, json
bluelink.0 | 2022-06-02 14:10:13.532 | warn | This object will not be created in future versions. Please report this to the developer.
bluelink.0 | 2022-06-02 14:10:13.531 | warn | Object  bluelink.0.xxx.driveHistory.20220601.regen is invalid:  obj.common.type has an invalid value (undefined) but has to be one of  number, string, boolean, array, object, mixed, file, json

</body>
</html>`

**Comment by Newan** [comment]
@TA2k  The problem is in yours function. It is possible to check it?

**Comment by Newan** [comment]
Yes see on #54

**Comment by Newan** [comment]
Thanks
