### ISSUE TITLE
No command for Control found for: bluelink.0.*.control.charge_stop

### ISSUE THREAD

**Issue by pos-ei-don** [Newan/ioBroker.bluelink#51]
I can not stop charging.
the other remote commands i tested work, like start charging, but when I try to stop i see this error in the Log.

Using the Android-App, bot, starting and stopping works.

**Comment by Duggles1301** [comment]
Same Problem here

**Comment by Newan** [comment]
pls check

**Comment by Duggles1301** [comment]
Still not working.
Log: No command for Control found for: bluelink.0.***.control.charge_stop
