### ISSUE TITLE
Bluelink App resets language when iobroker requests data

### ISSUE THREAD

**Issue by MrWeezle** [Newan/ioBroker.bluelink#52]
I was wondering why my bluelink app is resetting the language from german to english every day.
A service request at Hyundai Europe has revealed that having multiple apps open at the same time can cause that issue, especially when a third party program is using the API.

Original Response:
`vielen Dank für Ihre Rückmeldung. Dies ist sehr wahrscheinlich, wir haben von unserer technischen Abteilung die Information bekommen, dass das plötzliche zurücksetzen der Sprache, wenn es auftritt, auf Dritt-Anbieter Apps zurückzuführen ist.
`

Translation to english:
`thank you for your feedback. That is most likely the case, we got a response form our technical apartment which stated that the sudden reset of the language can be caused through third party apps.
`

Is there a way to prevent the reset of the language? I would not want to disable the iobroker integration but constantly changing the language in the app again to receive notifications in the correct language is very tedious.

**Comment by Newan** [comment]
Ich übergebe keine Sprache und habe derzeit keine Möglichkeit diese mitzugeben: https://bluelinky.readme.io/reference/examples

**Comment by MrWeezle** [comment]
Okay, danke. Dann werde ich mal nochmal an den Hyundai Support schreiben.
Ich geb Rückmeldung wenn ich neue Informationen habe.

**Comment by tsfuchs** [comment]
Ich denke dass bei der bluelinky Bibliothek die Sprache immer fest auf Englisch übergeben wird. Also müssten die die sprache abfragen/konfigurierbar machen um das Problem zu beheben.

**Comment by arteck** [comment]
fix is is PR

**Comment by Ilovegym66** [comment]
is fixed with the version from @arteck
