### ISSUE TITLE
plz managed the exception 

### ISSUE THREAD

**Issue by arteck** [Newan/ioBroker.bluelink#53]
![grafik](https://user-images.githubusercontent.com/6681528/188261979-ba5bb284-aedd-4211-b49b-34f2eb96c314.png)

my pin was wrong

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/188281891-4e7e7654-5c49-4e7f-bdd9-bb48c2286244.png)

new one bad request

**Comment by Newan** [comment]
Testversion online, with an try to fix this
