### ISSUE TITLE
object create before set and define the type

### ISSUE THREAD

**Issue by arteck** [Newan/ioBroker.bluelink#54]
![grafik](https://user-images.githubusercontent.com/6681528/188262505-1b688128-e1c3-4c39-be2a-61866518dafc.png)
![grafik](https://user-images.githubusercontent.com/6681528/188262546-66112915-5af3-459e-a09a-f3007a6c8f0e.png)

![grafik](https://user-images.githubusercontent.com/6681528/188262558-3ce8a70a-5091-42ed-81ea-ee5b62a2420a.png)

**Comment by Newan** [comment]
Duplicate #50

**Comment by TA2k** [comment]
@arteck If you can reproduce this after deleting the driverHistory Folder, a debug log would be very helpful
