### ISSUE TITLE
"Start clima fpr the vehicle" does not start also defrost, mirror heating etc.

### ISSUE THREAD

**Issue by derwilli** [Newan/ioBroker.bluelink#58]
Hi,

in the official Bluelink App, it is possible to check boxes to start steering wheel heating, defrost windscreen, rear window heating as well as side mirror heating. If the "Start Climate Control" botton in the app is pushed, als these features are also started.

Even if I have checked these boxes in the app, using the same account as the iobrooker instance. Setting "Start clima fpr the vehicle" to "true" in the iobrooker adapter does not start the other options. "Only" the AC is starting. Is there any way to make this happen?

I use a dash button at home, to trigger that event an heat my car, so I dont have to use the app. In winter it would be very convenient to also start the mentioned options as well.

Thanks for this adapter by the way =)

**Comment by tsfuchs** [comment]
Hello,

I've noticed the same problem with my ioniq5 and looked into the API calls of the Bluelink app. What I've discovered is that the library behind the ioBroker adapter, bluelinky, does not currently support activating these additional options and doesn't send the correct api calls.

I've created a GitHub issue on the bluelinky repository to bring this to the attention of the developers (https://github.com/Hacksore/bluelinky/issues/230). Lets see what cames out of that.

**Comment by arteck** [comment]
check the GIT version

**Comment by thoeckerde** [comment]
Hi,
first: Thanks, for the grate Job.

i have the same problem.

If I start the defrost with the connect-App, the RAW data in the objektlist is vehicleStatus.steerWheelHeat = 2
So it look not like a boolean.

**Comment by arteck** [comment]
> the RAW data in the objektlist shows vehicleStatus.steerWheelHeat = 2

can you post the RAW Data plz
