### ISSUE TITLE
Update 2.2.5 ==> 2.2.6 endless

### ISSUE THREAD

**Issue by eric2905** [Newan/ioBroker.bluelink#59]
After updating from v 2.2.5 to v2.2.6, the update is still in the update list.
Forgotten to increase the version during update?

**Comment by arteck** [comment]
npm package is wrong

**Comment by tomkotti** [comment]
version 2.2.6 uses osx-temperature-sensor, which is only intended for mac-os. 
that's why the installation doesn't go through
Am I correct?

**Comment by Michaelnorge** [comment]
Yes, download from GIT fixed problem!
