### ISSUE TITLE
Seit Update auf 1.0.4 kein Login mehr möglich (KIA)

### ISSUE THREAD

**Issue by luebke01** [Newan/ioBroker.bluelink#8]
Ich habe heute von der Version 1.0.3 auf die Version 1.0.4 upgedatet.
Seit dem bekomme ich mit dme ioBroker keine VErbindung mehr.
Der Logauszug sagt folgendes:
(4719) starting. Version 1.0.4 in /opt/iobroker/node_modules/iobroker.bluelink, node: v12.22.1, js-controller: 3.2.16
(4719) Login to api
(4719) ManagedBluelinkyError: @EuropeController.login: [401] Unauthorized on [POST] https://prd.eu-ccapi.kia.com:8080/api/v1/spa/notifications/register - {"retCode":"F","resCode":"4017","resMsg":"Invalid Application ID.","msgId":"cfded5e9-b659-41b1-ad1a-335720b25e66")

Die Zugangsdaten sind weiterhin im Adapter vorhanden.

**Comment by Newan** [comment]
Trage bitte nochmal die Daten ein. Das Passwort wird anders verschlüsselt

**Comment by luebke01** [comment]
Ich habe alle DAten (Passwort/PIN/Nutzername) neu eingegeben. Der Fehler ist gleich geblieben. Erst das Entfernen vom Adapter 1.0.4 und Neuinstallation 1.0.4 war dann erfolgreich. Trotzdem danke für den super Adapter.
