### ISSUE TITLE
12 Battery drained to 5V, despite setting to prevent it

### ISSUE THREAD

**Issue by gidhap** [Newan/ioBroker.bluelink#90]
By accident, in the instance settings, I entered 100 Requests per day. I did want 3 only, so my fault.
However, the setting to protect the battery did not work. Today the battery was drained to 5 volts, so I had to manually open the vehicle and recharge the battery. Hope Battery isn't dead.
Txs for taking care
![image](https://github.com/Newan/ioBroker.bluelink/assets/28500973/92e7e038-795f-4f50-a44e-b626e1aeecec)

**Comment by arteck** [comment]
it works but.. check plz in the tree ..  under object control. ypu can set ehre also a soc_battery min state
