### ISSUE TITLE
Adapter bring Fehler nach Update JS-Controller 5.0.3

### ISSUE THREAD

**Issue by cybermann22** [Newan/ioBroker.bluelink#95]
`<html>
<body>

bluelink.0 | 2023-06-14 13:29:56.365 | error | unhandled promise rejection: undefined is not a valid state value
-- | -- | -- | --
bluelink.0 | 2023-06-14 13:29:56.364 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
bluelink.0 | 2023-06-14 13:29:56.350 | error | undefined is not a valid state value
bluelink.0 | 2023-06-14 13:29:56.350 | error | Error: undefined is not a valid state value at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17) at Bluelink._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5372:49) at Bluelink.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5333:21) at Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:121:34) at async Json2iob.extractArray (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:253:17) at async Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:90:21) at async Bluelink.receiveEVInformation (/opt/iobroker/node_modules/iobroker.bluelink/main.js:383:17) at async ae.<anonymous> (/opt/iobroker/node_modules/iobroker.bluelink/main.js:222:25)
bluelink.0 | 2023-06-14 13:29:56.350 | error | unhandled promise rejection: undefined is not a valid state value
bluelink.0 | 2023-06-14 13:29:56.349 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

**Comment by arteck** [comment]
adapter version ??
