### ISSUE TITLE
"Start Clima" und "Vehicle charge limit" funktioniert nicht bei Kia EV6

### ISSUE THREAD

**Issue by nikmaier** [Newan/ioBroker.bluelink#96]
Hallo,
Habe aktuelle Git-Version installiert.
Als Fahrzeug habe ich einen Kia EV6 GT (Baujahr 2023).
Klima starten und auch Limit setzen funktioniert in der Kia Connect App einwandfrei.
Im Adapter werden Werte auch alle richtig angezeigt, auch aufsperren oder zusperren funktioniert, sogar "Stop Clima" funktioniert. aber leider hat bei mir "Start Clima" und "Vehicle charge limit" im Adapter keine Funktion.

1. Beispiel Ladelimit:
Wenn ich unter dem Objekt "charge_limit_slow" den Wert ändere z.B. auf 90, dann ändert es sich nicht im Auto und auch nicht in der App, im Log wird auch nichts angezeigt und beim nächsten Refresh wird der Wert im Iobroker wieder auf den vorherigen Wert überschrieben:

![image](https://github.com/Newan/ioBroker.bluelink/assets/69574329/bdf9f90d-0fbc-41e8-9ef0-f17d94fd0aff)

2. Beispiel Klimaanlagen Start:
Ich stelle die Werte für die Klima ein:
![image](https://github.com/Newan/ioBroker.bluelink/assets/69574329/98c841f7-5b71-4166-8ec8-3dc7e0829521)

Danach starte ich die Klima mit dem Button des Objekts start:
![image](https://github.com/Newan/ioBroker.bluelink/assets/69574329/83e103d8-c6c7-4b7a-bb5d-d78d76d3d27a)

Im Log sieht man danach auch den Eintrag:
![image](https://github.com/Newan/ioBroker.bluelink/assets/69574329/39b329be-ce9f-4561-af00-35f62e2fa44e)

Aber im Auto startet die Klima nicht, ebenso sieht man in der App das die Klima nicht gestartet wurde:
![image](https://github.com/Newan/ioBroker.bluelink/assets/69574329/11f6ac11-09e8-4752-b9b1-fa8b5bc864ba)

Nach einigen Minuten kommt allerdings die Kia Connect Push Meldung (obwohl die Klima nicht läuft):
![image](https://github.com/Newan/ioBroker.bluelink/assets/69574329/f7e035d5-399d-464e-acdc-5571371c3c87)

Als Gegentest habe ich jetzt kurz mal Homeassist installiert und dort den Kia Adapter installiert, dort funktioniert der Klimastart und auch die Ladelimit einstellung sofort.

Es muss also irgendeine Kleinigkeit im Iobroker Adapter bzw. dem Api Aufruf sein.

Wäre wirklich sehr sehr dankbar für die Hilfe. 

Danke im Voraus.

**Comment by arteck** [comment]
so einz nach dem anderen

installiere bitte 

https://github.com/Newan/ioBroker.bluelink/tarball/issue96

und schaue erstmal ob es mit der klima klappt

**Comment by nikmaier** [comment]
Hi arteck,
vielen lieben Dank für deine Rückmeldung.

Habe den Link über Github Katze installiert (ist schon richtig so oder?):

![image](https://github.com/Newan/ioBroker.bluelink/assets/69574329/4b8c7300-73ff-4289-a7aa-a2043930199c)

Hab dann gestartet:

![image](https://github.com/Newan/ioBroker.bluelink/assets/69574329/59480c1f-2e76-40c5-865f-a8044a6be2eb)

... klappt leider noch nicht.

**Comment by arteck** [comment]
getestet und funktioniert.
